apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking
  labels:
    app: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking
  template:
    metadata:
      labels:
        app: parking
    spec:
      containers:
      - name: parking
        image: pz/parking:latest
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: parking
  labels:
    app: parking
spec:
  type: NodePort
  selector:
    app: parking
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30501